package com.SmartHealthRemoteSystem.SHSR.RadiologyRequestScheduling.model;

import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.TypeAlias;
import org.springframework.data.mongodb.core.index.Indexed;
import org.springframework.data.mongodb.core.mapping.Document;

import java.util.Date;

/**
 * MongoDB document representing a doctor's imaging request for a patient.
 * Collection: RadiologyRequest
 *
 * UCR008 — submitted by Doctor
 * UCR009 — approved or rejected by Radiologist / Radiographer
 * UCR011 — priorityScore computed by PrioritizationService at submission
 * UCR014 — cancelled by Radiologist / Radiographer with reason
 *
 * NOTE: _id is a UUID auto-generated by MongoDB.
 *       requestId is a separate human-readable sequential ID (REQ000001 format).
 */
@Document(collection = "RadiologyRequest")
@TypeAlias("com.SmartHealthRemoteSystem.SHSR.RadiologyRequestScheduling.ImagingRequest")
public class ImagingRequest {

    /** MongoDB internal _id — UUID, auto-assigned, never exposed to business logic. */
    @Id
    private String id;

    /** Human-readable sequential request ID (REQ000001). Used as the business key. */
    @Indexed(unique = true, sparse = true)
    private String requestId;

    @Indexed
    private String patientId;

    @Indexed
    private String doctorId;

    private Modality      modality;
    private String        bodyPart;
    private UrgencyLevel  urgencyLevel;
    private String        clinicalNotes;
    private String        referringPhysician;
    private Integer       priorityScore;

    @Indexed
    private RequestStatus status;

    private String        rejectionReason;
    private String        cancellationReason;
    private String        cancelledBy;
    private String        cancelledByRole;

    /** Radiologist / Radiographer who approved or rejected the request. */
    private String        radiologistId;

    private Date          createdDate;
    private Date          updatedDate;

    public ImagingRequest() {}

    public ImagingRequest(String id, String requestId, String patientId, String doctorId,
                          Modality modality, String bodyPart,
                          UrgencyLevel urgencyLevel, String clinicalNotes,
                          String referringPhysician, Integer priorityScore,
                          RequestStatus status, String rejectionReason,
                          String cancellationReason, String cancelledBy,
                          String cancelledByRole, String radiologistId,
                          Date createdDate, Date updatedDate) {
        this.id                 = id;
        this.requestId          = requestId;
        this.patientId          = patientId;
        this.doctorId           = doctorId;
        this.modality           = modality;
        this.bodyPart           = bodyPart;
        this.urgencyLevel       = urgencyLevel;
        this.clinicalNotes      = clinicalNotes;
        this.referringPhysician = referringPhysician;
        this.priorityScore      = priorityScore;
        this.status             = status;
        this.rejectionReason    = rejectionReason;
        this.cancellationReason = cancellationReason;
        this.cancelledBy        = cancelledBy;
        this.cancelledByRole    = cancelledByRole;
        this.radiologistId      = radiologistId;
        this.createdDate        = createdDate;
        this.updatedDate        = updatedDate;
    }

    // --- Getters ---
    public String        getId()                  { return id; }
    public String        getRequestId()           { return requestId; }
    public String        getPatientId()           { return patientId; }
    public String        getDoctorId()            { return doctorId; }
    public Modality      getModality()            { return modality; }
    public String        getBodyPart()            { return bodyPart; }
    public UrgencyLevel  getUrgencyLevel()        { return urgencyLevel; }
    public String        getClinicalNotes()       { return clinicalNotes; }
    public String        getReferringPhysician()  { return referringPhysician; }
    public Integer       getPriorityScore()       { return priorityScore; }
    public RequestStatus getStatus()              { return status; }
    public String        getRejectionReason()     { return rejectionReason; }
    public String        getCancellationReason()  { return cancellationReason; }
    public String        getCancelledBy()         { return cancelledBy; }
    public String        getCancelledByRole()     { return cancelledByRole; }
    public String        getRadiologistId()       { return radiologistId; }
    public Date          getCreatedDate()         { return createdDate; }
    public Date          getUpdatedDate()         { return updatedDate; }

    // --- Setters ---
    public void setId(String v)                   { this.id = v; }
    public void setRequestId(String v)            { this.requestId = v; }
    public void setPatientId(String v)            { this.patientId = v; }
    public void setDoctorId(String v)             { this.doctorId = v; }
    public void setModality(Modality v)           { this.modality = v; }
    public void setBodyPart(String v)             { this.bodyPart = v; }
    public void setUrgencyLevel(UrgencyLevel v)   { this.urgencyLevel = v; }
    public void setClinicalNotes(String v)        { this.clinicalNotes = v; }
    public void setReferringPhysician(String v)   { this.referringPhysician = v; }
    public void setPriorityScore(Integer v)       { this.priorityScore = v; }
    public void setStatus(RequestStatus v)        { this.status = v; }
    public void setRejectionReason(String v)      { this.rejectionReason = v; }
    public void setCancellationReason(String v)   { this.cancellationReason = v; }
    public void setCancelledBy(String v)          { this.cancelledBy = v; }
    public void setCancelledByRole(String v)      { this.cancelledByRole = v; }
    public void setRadiologistId(String v)        { this.radiologistId = v; }
    public void setCreatedDate(Date v)            { this.createdDate = v; }
    public void setUpdatedDate(Date v)            { this.updatedDate = v; }

    // --- Builder ---
    public static Builder builder() { return new Builder(); }

    public static class Builder {
        private String        id;
        private String        requestId;
        private String        patientId;
        private String        doctorId;
        private Modality      modality;
        private String        bodyPart;
        private UrgencyLevel  urgencyLevel;
        private String        clinicalNotes;
        private String        referringPhysician;
        private Integer       priorityScore;
        private RequestStatus status;
        private String        rejectionReason;
        private String        cancellationReason;
        private String        cancelledBy;
        private String        cancelledByRole;
        private String        radiologistId;
        private Date          createdDate;
        private Date          updatedDate;

        public Builder id(String v)                   { this.id = v;               return this; }
        public Builder requestId(String v)            { this.requestId = v;        return this; }
        public Builder patientId(String v)            { this.patientId = v;        return this; }
        public Builder doctorId(String v)             { this.doctorId = v;         return this; }
        public Builder modality(Modality v)           { this.modality = v;         return this; }
        public Builder bodyPart(String v)             { this.bodyPart = v;         return this; }
        public Builder urgencyLevel(UrgencyLevel v)   { this.urgencyLevel = v;     return this; }
        public Builder clinicalNotes(String v)        { this.clinicalNotes = v;    return this; }
        public Builder referringPhysician(String v)   { this.referringPhysician=v; return this; }
        public Builder priorityScore(Integer v)       { this.priorityScore = v;    return this; }
        public Builder status(RequestStatus v)        { this.status = v;           return this; }
        public Builder rejectionReason(String v)      { this.rejectionReason = v;  return this; }
        public Builder cancellationReason(String v)   { this.cancellationReason=v; return this; }
        public Builder cancelledBy(String v)          { this.cancelledBy = v;      return this; }
        public Builder cancelledByRole(String v)      { this.cancelledByRole = v;  return this; }
        public Builder radiologistId(String v)        { this.radiologistId = v;    return this; }
        public Builder createdDate(Date v)            { this.createdDate = v;      return this; }
        public Builder updatedDate(Date v)            { this.updatedDate = v;      return this; }

        public ImagingRequest build() {
            return new ImagingRequest(id, requestId, patientId, doctorId,
                    modality, bodyPart, urgencyLevel, clinicalNotes, referringPhysician,
                    priorityScore, status, rejectionReason, cancellationReason,
                    cancelledBy, cancelledByRole, radiologistId,
                    createdDate, updatedDate);
        }
    }
}