spring.mvc.hiddenmethod.filter.enabled=true
server.tomcat.remoteip.remote-ip-header=x-forwarded-for
server.tomcat.remoteip.protocol-header=x-forwarded-proto

server.port=${PORT:8080}
server.error.whitelabel.enabled=false
logging.level.org.springframework.data.mongodb.core.MongoTemplate=DEBUG



spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=wellcheck2025@gmail.com
spring.mail.password=lyzh vpqw tvwd qock
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

logging.level.org.springframework.mail=DEBUG
spring.profiles.active=local


spring.data.mongodb.uri=mongodb+srv://admin:admin@atlascluster.htlbqbu.mongodb.net/?retryWrites=true&w=majority&appName=AtlasCluster
spring.data.mongodb.database=Wellcheck2

# ML API running on Azure
ml.api.url=https://diseasepredictorapi.azurewebsites.net/status/

